# Generated by Django 4.1.6 on 2023-02-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_registeration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobileno', models.CharField(max_length=19)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
